### ISSUE TITLE
The plugin cause a Python error when loading a mesh layer in QGIS 3.36.2

### ISSUE THREAD

**Issue by Amalvir** [vcloarec/meshflow#9]
Hi !

There is a Python error raised when I load a mesh layer in a project. I don't try to use the plugin, it is just activate, I load a mesh layer (no matter the extension of it) and the following error raised.

This error don't show in the 3.36.1 or below.
The mesh layers load fine despite the error.
The same issue is raised when I load a project with mesh layers.
 
```
Traceback (most recent call last):
  File "C:\OSGeo4W\apps\Python312\Lib\site-packages\decorator.py", line 231, in fun
    args, kw = fix(args, kw, sig)
               ^^^^^^^^^^^^^^^^^^
  File "C:\OSGeo4W\apps\Python312\Lib\site-packages\decorator.py", line 203, in fix
    ba = sig.bind(*args, **kwargs)
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\OSGeo4W\apps\Python312\Lib\inspect.py", line 3242, in bind
    return self._bind(args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\OSGeo4W\apps\Python312\Lib\inspect.py", line 3163, in _bind
    raise TypeError('too many positional arguments') from None
TypeError: too many positional arguments
```

Thank you !

**Comment by nicogodet** [comment]
Hi @Amalvir 
I suspected this plugin was the culprit when you raised the issue on QGIS repo.
As I add a decorator in this plugin, I will look into it.

**Comment by vcloarec** [comment]
Hi all, I confirm, it seems to come from the wait cursor decorator added by @nicogodet, maybe python 3.12 need another implementation if this decorator.

**Comment by vcloarec** [comment]
The issue is fixed and the plugin is updated. Thanks @nicogodet  for the fix and thanks @Amalvir to have report it !
